Clone remote branches

diff --git a/install/oe-checkout b/install/oe-checkout
--- a/install/oe-checkout
+++ b/install/oe-checkout
@@ -43,7 +43,7 @@ case $i in
 		## nomigrate will prevent database migrations from running automatically at the end of checkout
 		;;
 	--root|-r|--r|--remote) customgitroot=1
-		## Await custom root for git repo in net parameter
+		## Await custom root for git repo in next parameter
 		;;
 	--no-summary) nosummary=1
 		## don't show summary of checkout at completion
@@ -147,7 +147,13 @@ if [ ! -d ".git " ]; then
 	# checkout branch. If branch doesn't exist then get default instead
 	if ! git clone -b $branch https://github.com/$gitroot/openeyes ./ ; then 
 		echo "$branch doesn't exist. Falling back to $defaultbranch branch for openeyes..."
-		git clone -b $defaultbranch https://github.com/$gitroot/openeyes ./
+		if ! git clone -b $defaultbranch https://github.com/$gitroot/openeyes ./ ; then
+			# If we cannot find default branch at specifeid remote, fall back to OE git hub
+			if [ "$gitroot != "openeyes ]; then
+				echo "could not find $defaultbranch at $gitroot remote. Falling back to openeyes official repo"
+				git clone -b $defaultbranch https://github.com/openeyes/openeyes ./
+			fi
+		fi
 	fi
 else
 	printf "\e[32mopeneyes: \e[0m"
@@ -172,7 +178,13 @@ for module in ${modules[@]}; do
 			# checkout branch. If branch doesn't exist then get master instead
 			if ! git clone -b $branch https://github.com/$gitroot/$module; then 
 				echo "falling back to $defaultbranch branch for $module..."
-				git clone -b $defaultbranch https://github.com/$gitroot/$module 
+				if ! git clone -b $defaultbranch https://github.com/$gitroot/$module 
+					# If we cannot find default branch at specifeid remote, fall back to OE git hub
+					if [ "$gitroot != "openeyes ]; then
+						echo "could not find $defaultbranch at $gitroot remote. Falling back to openeyes official repo"
+						git clone -b $defaultbranch https://github.com/openeyes/$module./
+					fi
+				fi
 			fi
 		fi
   else
